name: Deploy to K3s

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config get-contexts

    - name: Deploy Nginx
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f nginx-deployment.yaml --validate=false
